when:
  event: [push, manual]

# Clone the repo as usual so the Dockerfile can COPY the workspace
skip_clone: false

steps:
  - name: tests
    image: python:3.13-slim
    environment:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_ROOT_USER_ACTION: ignore
    commands:
      - apt-get update && apt-get install -y --no-install-recommends ffmpeg libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
      - python -m pip install --upgrade pip
      - pip install --no-cache-dir -r requirements.txt pytest
      - pytest -q

  - name: docker-build-and-push
    image: docker:stable
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      GHCR_USER:
        from_secret: ghcr_user
      GHCR_TOKEN:
        from_secret: ghcr_token
    commands:
      - docker login ghcr.io -u $${GHCR_USER} -p $${GHCR_TOKEN}
      - |
        docker build \
          --pull \
          --file images/WplaceRecorder/Dockerfile \
          --tag ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest \
          .
      - docker push ghcr.io/${CI_REPO_OWNER}/${CI_REPO_NAME}:latest
    depends_on:
      - tests
    when:
      branch:
        - main

  - name: trigger-portainer-stack-update
    image: curlimages/curl:8.5.0
    environment:
      PORTAINER_WEBHOOK_URL:
        from_secret: portainer_webhook_url
    commands:
      - |
        if [ -z "$${PORTAINER_WEBHOOK_URL}" ]; then
          echo "PORTAINER_WEBHOOK_URL secret not set" >&2
          exit 1
        fi
        curl -fsS -X POST "$${PORTAINER_WEBHOOK_URL}"
    depends_on:
      - docker-build-and-push
    when:
      branch:
        - main
